--- 
- name: "Add NodeJS from NodaSource"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash 

- name: "Install NodeJS 13"
  become: true
  apt:
    name: ["nodejs"]
    staet: latest 
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2 
    global: yes 